	class itc_land_g155hex: itc_land_how_mag {
		author = "Toadball";
		displayName = "G155 HE";
		ammo = "itc_land_155mm";
		muzzleImpulseFactor[] = {15, 30};
		displayNameShort = "G155 HE";
		itc_land_fuze = "mof35_mod0";
		itc_land_submunition = "itc_land_155mm_helper";
		itc_land_charge_format = "itc_land_g155hex_chg%1";
		itc_land_CountInAH = 1;
		itc_land_maxChargeIndex = 5;
		itc_land_btabListFile = "itc_land_ballistics\tables\g_155\list.sqf";
	};
	class itc_land_g155hex_chg1: itc_land_g155hex { initSpeed = 100; itc_land_CountInAH = 0;  };
	class itc_land_g155hex_chg2: itc_land_g155hex { initSpeed = 200; itc_land_CountInAH = 0;  };
	class itc_land_g155hex_chg3: itc_land_g155hex { initSpeed = 300; itc_land_CountInAH = 0;  };
	class itc_land_g155hex_chg4: itc_land_g155hex { initSpeed = 400; itc_land_CountInAH = 0;  };
	class itc_land_g155hex_chg5: itc_land_g155hex { initSpeed = 500; itc_land_CountInAH = 0;  };

	class itc_land_g155smo: itc_land_how_mag {
		author = "Toadball";
		displayName = "G155 SMOKE";
		//ammo = "itc_land_155mm_inert";
		ammo = "itc_land_155mm_smoke";
		muzzleImpulseFactor[] = {15, 30};
		displayNameShort = "G155 SMOKE";
		itc_land_fuze = "mof35_mod4";
		itc_land_charge_format = "itc_land_g155smo_chg%1";
		itc_land_CountInAH = 1;
		itc_land_maxChargeIndex = 5;
		itc_land_submunition = "itc_land_155mm_smoke";
		itc_land_timeModifier = -1.5;
		itc_land_btabListFile = "itc_land_ballistics\tables\g_155\list.sqf";
	};
	class itc_land_g155smo_chg1: itc_land_g155smo { initSpeed = 100; itc_land_CountInAH = 0;  };
	class itc_land_g155smo_chg2: itc_land_g155smo { initSpeed = 200; itc_land_CountInAH = 0;  };
	class itc_land_g155smo_chg3: itc_land_g155smo { initSpeed = 300; itc_land_CountInAH = 0;  };
	class itc_land_g155smo_chg4: itc_land_g155smo { initSpeed = 400; itc_land_CountInAH = 0;  };
	class itc_land_g155smo_chg5: itc_land_g155smo { initSpeed = 500; itc_land_CountInAH = 0;  };

	class itc_land_g155icm: itc_land_how_mag {
		author = "Toadball";
		displayName = "G155 ICM";
		ammo = "itc_land_155mm_inert";
		itc_land_submunition = "itc_land_155mm_dpicm_helper";
		muzzleImpulseFactor[] = {15, 30};
		displayNameShort = "G155 ICM";
		itc_land_fuze = "mof35_mod1";
		itc_land_charge_format = "itc_land_g155icm_chg%1";
		itc_land_CountInAH = 1;
		itc_land_maxChargeIndex = 5;
		itc_land_timeModifier = -2;
		itc_land_btabListFile = "itc_land_ballistics\tables\g_155\list.sqf";
	};
	class itc_land_g155icm_chg1: itc_land_g155icm { initSpeed = 100; itc_land_CountInAH = 0;  };
	class itc_land_g155icm_chg2: itc_land_g155icm { initSpeed = 200; itc_land_CountInAH = 0;  };
	class itc_land_g155icm_chg3: itc_land_g155icm { initSpeed = 300; itc_land_CountInAH = 0;  };
	class itc_land_g155icm_chg4: itc_land_g155icm { initSpeed = 400; itc_land_CountInAH = 0;  };
	class itc_land_g155icm_chg5: itc_land_g155icm { initSpeed = 500; itc_land_CountInAH = 0;  };

	class itc_land_g155mat: itc_land_how_mag {
		author = "Toadball";
		displayName = "G155 MINE-AT";
		ammo = "itc_land_155mm_inert";
		muzzleImpulseFactor[] = {15, 30};
		displayNameShort = "G155 MAT";
		itc_land_fuze = "mof35_mod1";
		itc_land_charge_format = "itc_land_g155mat_chg%1";
		itc_land_CountInAH = 1;
		itc_land_maxChargeIndex = 5;
		itc_land_timeModifier = -1.2;
		itc_land_submunition = "itc_land_155mm_fascam_at_helper";
		itc_land_btabListFile = "itc_land_ballistics\tables\g_155\list.sqf";
	};
	class itc_land_g155mat_chg1: itc_land_g155mat { initSpeed = 100; itc_land_CountInAH = 0;  };
	class itc_land_g155mat_chg2: itc_land_g155mat { initSpeed = 200; itc_land_CountInAH = 0;  };
	class itc_land_g155mat_chg3: itc_land_g155mat { initSpeed = 300; itc_land_CountInAH = 0;  };
	class itc_land_g155mat_chg4: itc_land_g155mat { initSpeed = 400; itc_land_CountInAH = 0;  };
	class itc_land_g155mat_chg5: itc_land_g155mat { initSpeed = 500; itc_land_CountInAH = 0;  };

	class itc_land_g155map: itc_land_how_mag {
		author = "Toadball";
		displayName = "G155 MINE-AP";
		ammo = "itc_land_155mm_inert";
		muzzleImpulseFactor[] = {15, 30};
		displayNameShort = "G155 MAP";
		itc_land_fuze = "mof35_mod1";
		itc_land_charge_format = "itc_land_g155map_chg%1";
		itc_land_CountInAH = 1;
		itc_land_maxChargeIndex = 5;
		itc_land_timeModifier = -1.5;
		itc_land_submunition = "itc_land_155mm_fascam_ap_helper";
		itc_land_btabListFile = "itc_land_ballistics\tables\g_155\list.sqf";
	};
	class itc_land_g155map_chg1: itc_land_g155map { initSpeed = 100; itc_land_CountInAH = 0;  };
	class itc_land_g155map_chg2: itc_land_g155map { initSpeed = 200; itc_land_CountInAH = 0;  };
	class itc_land_g155map_chg3: itc_land_g155map { initSpeed = 300; itc_land_CountInAH = 0;  };
	class itc_land_g155map_chg4: itc_land_g155map { initSpeed = 400; itc_land_CountInAH = 0;  };
	class itc_land_g155map_chg5: itc_land_g155map { initSpeed = 500; itc_land_CountInAH = 0;  };

	class itc_land_g155pgm: itc_land_how_mag {
		author = "Toadball";
		initSpeed = 162;
		displayName = "G155 GPS GUIDED";
		ammo = "itc_land_155mm";
		muzzleImpulseFactor[] = {15, 30};
		displayNameShort = "G155 PGM";
		itc_land_fuze = "mof35_mod2";
		itc_land_guidance[] = {"gps_inertial","itc_land_guidance_fnc_pgm15x"};
		itc_land_submunition = "itc_land_155mm_helper";
		itc_land_charge_format = "itc_land_g155pgm_chg%1";
		itc_land_CountInAH = 1;
		itc_land_maxChargeIndex = 5;
		itc_land_btabListFile = "itc_land_ballistics\tables\g_155\list.sqf";
	};
	class itc_land_g155pgm_chg1: itc_land_g155pgm { initSpeed = 100; itc_land_CountInAH = 0;  };
	class itc_land_g155pgm_chg2: itc_land_g155pgm { initSpeed = 200; itc_land_CountInAH = 0;  };
	class itc_land_g155pgm_chg3: itc_land_g155pgm { initSpeed = 300; itc_land_CountInAH = 0;  };
	class itc_land_g155pgm_chg4: itc_land_g155pgm { initSpeed = 400; itc_land_CountInAH = 0;  };
	class itc_land_g155pgm_chg5: itc_land_g155pgm { initSpeed = 500; itc_land_CountInAH = 0;  };

	class itc_land_g155lgm: itc_land_how_mag {
		author = "Toadball";
		displayName = "G155 LASER GUIDED";
		ammo = "itc_land_155mm";
		muzzleImpulseFactor[] = {15, 30};
		displayNameShort = "G155 LGM";
		itc_land_fuze = "mof35_mod2";
		itc_land_guidance[] = {"laser_coded","itc_land_guidance_fnc_lgm15x"};
		itc_land_submunition = "itc_land_155mm_helper";
		itc_land_charge_format = "itc_land_g155lgm_chg%1";
		itc_land_CountInAH = 1;
		itc_land_maxChargeIndex = 5;
		itc_land_btabListFile = "itc_land_ballistics\tables\g_155\list.sqf";
	};
	class itc_land_g155lgm_chg1: itc_land_g155lgm { initSpeed = 100; itc_land_CountInAH = 0;  };
	class itc_land_g155lgm_chg2: itc_land_g155lgm { initSpeed = 200; itc_land_CountInAH = 0;  };
	class itc_land_g155lgm_chg3: itc_land_g155lgm { initSpeed = 300; itc_land_CountInAH = 0;  };
	class itc_land_g155lgm_chg4: itc_land_g155lgm { initSpeed = 400; itc_land_CountInAH = 0;  };
	class itc_land_g155lgm_chg5: itc_land_g155lgm { initSpeed = 500; itc_land_CountInAH = 0;  };

	class itc_land_g155ill: itc_land_how_mag {
		author = "Toadball";
		initSpeed = 162;
		displayName = "G155 ILLUM";
		ammo = "itc_land_155mm_inert";
		muzzleImpulseFactor[] = {15, 30};
		displayNameShort = "G155 ILLUM";
		itc_land_submunition = "itc_land_155mm_illum";
		itc_land_fuze = "mof35_mod1";
		itc_land_charge_format = "itc_land_g155ill_chg%1";
		itc_land_CountInAH = 1;
		itc_land_maxChargeIndex = 5;
		itc_land_heightModifier = 200;
		itc_land_btabListFile = "itc_land_ballistics\tables\g_155\list.sqf";
	};
	class itc_land_g155ill_chg1: itc_land_g155ill { initSpeed = 100; itc_land_CountInAH = 0;  };
	class itc_land_g155ill_chg2: itc_land_g155ill { initSpeed = 200; itc_land_CountInAH = 0;  };
	class itc_land_g155ill_chg3: itc_land_g155ill { initSpeed = 300; itc_land_CountInAH = 0;  };
	class itc_land_g155ill_chg4: itc_land_g155ill { initSpeed = 400; itc_land_CountInAH = 0;  };
	class itc_land_g155ill_chg5: itc_land_g155ill { initSpeed = 500; itc_land_CountInAH = 0;  };

	class itc_land_g155ext: itc_land_how_mag {
		author = "Yax";
		initSpeed = 162;
		displayName = "G155 EXTRA";
		ammo = "itc_land_155mm_inert";
		itc_land_submunitionCount = 2;
		itc_land_submunitionScript = "itc_land_veh_weapons_fnc_deployExtra";
		itc_land_heightModifier = 50;
		itc_land_timeModifier = -5;
		muzzleImpulseFactor[] = {15, 30};
		displayNameShort = "G155 EXTRA";
		itc_land_fuze = "mof35_mod3";
		itc_land_charge_format = "itc_land_g155ext_chg%1";
		itc_land_CountInAH = 1;
		itc_land_maxChargeIndex = 5;
		itc_land_btabListFile = "itc_land_ballistics\tables\g_155\list.sqf";
	};
	class itc_land_g155ext_chg1: itc_land_g155ext { initSpeed = 100; itc_land_CountInAH = 0;  };
	class itc_land_g155ext_chg2: itc_land_g155ext { initSpeed = 200; itc_land_CountInAH = 0;  };
	class itc_land_g155ext_chg3: itc_land_g155ext { initSpeed = 300; itc_land_CountInAH = 0;  };
	class itc_land_g155ext_chg4: itc_land_g155ext { initSpeed = 400; itc_land_CountInAH = 0;  };
	class itc_land_g155ext_chg5: itc_land_g155ext { initSpeed = 500; itc_land_CountInAH = 0;  };

	class itc_land_g155falat: itc_land_how_mag {
		author = "Yax";
		initSpeed = 162;
		displayName = "G155 FALAT";
		ammo = "itc_land_155mm_inert";
		itc_land_submunitionCount = 2;
		itc_land_submunitionScript = "itc_land_veh_weapons_fnc_deployFalat";
		itc_land_guidance[] = {"laser_coded_2"};
		itc_land_heightModifier = 50;
		itc_land_timeModifier = -5;
		muzzleImpulseFactor[] = {15, 30};
		displayNameShort = "G155 FALAT";
		itc_land_fuze = "mof35_mod3";
		itc_land_charge_format = "itc_land_g155falat_chg%1";
		itc_land_CountInAH = 1;
		itc_land_maxChargeIndex = 5;
		itc_land_btabListFile = "itc_land_ballistics\tables\g_155\list.sqf";
	};
	class itc_land_g155falat_chg1: itc_land_g155falat { initSpeed = 100; itc_land_CountInAH = 0;  };
	class itc_land_g155falat_chg2: itc_land_g155falat { initSpeed = 200; itc_land_CountInAH = 0;  };
	class itc_land_g155falat_chg3: itc_land_g155falat { initSpeed = 300; itc_land_CountInAH = 0;  };
	class itc_land_g155falat_chg4: itc_land_g155falat { initSpeed = 400; itc_land_CountInAH = 0;  };
	class itc_land_g155falat_chg5: itc_land_g155falat { initSpeed = 500; itc_land_CountInAH = 0;  };
