itc_land_spike_cameraMode = "";
itc_land_spike_camera = nil;
itc_land_spike_currentMissile = nil;
itc_land_spike_lockInformation = [nil, [0,0,0], nil, [0,0,0]];
itc_land_spike_traverseModifier = 0.05;
itc_land_spike_launchTime = 0;
itc_land_spike_wobble = [-1, 15, 0.25];
itc_land_spike_debug = false;
itc_land_spike_ppEffect = false;
